## 1

get http://localhost:3000/players

### 2
get http://localhost:3000/players/2/

### 3
put http://localhost:3000/players/2/
Content-Type: application/json

{
    "playerName": "mouli"
}

### 4

get http://localhost:3000/matches/5/

### 5 *

get http://localhost:3000/players/1/matches

### 6 *
get http://localhost:3000/matches/10/players


### 7 *
get http://localhost:3000/players/1/playerScores

###